apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - route.yaml
commonLabels:
  app: squad-1-project
  app.kubernetes.io/instance: squad-1-project-instance
  app.kubernetes.io/name: squad-1-project
