apiVersion: v1
kind: Service
metadata:
  labels:
    app: squad-1-project
    app.kubernetes.io/instance: squad-1-project
    app.kubernetes.io/name: squad-1-project-squad-1-project
  name: squad-1-project
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: squad-1-project
    app.kubernetes.io/instance: squad-1-project
    app.kubernetes.io/name: squad-1-project-squad-1-project
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.openshift.io/vcs-ref: f7580aa1eb6f7176705176e201ecff4de93edafb
    app.openshift.io/vcs-uri: https://github.com/cloud-native-garage-method-cohort/squad-1-project
  labels:
    app: squad-1-project
    app.kubernetes.io/instance: squad-1-project
    app.kubernetes.io/name: squad-1-project-squad-1-project
    app.openshift.io/runtime: js
  name: buildah-assignment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: squad-1-project
      app.kubernetes.io/instance: squad-1-project
      app.kubernetes.io/name: squad-1-project-squad-1-project
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: squad-1-project
        app.kubernetes.io/instance: squad-1-project
        app.kubernetes.io/name: squad-1-project-squad-1-project
    spec:
      containers:
      - env:
        - name: INGRESS_HOST
        - name: PROTOCOLS
        - name: LOG_LEVEL
          value: debug
        image: quay.io/fabianschwab/emea-3-squad-1-project:d48622f943d47bc1ee21ebd786f76b01974d6322
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: buildah-assignment
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
    openshift.io/host.generated: "true"
  labels:
    app: squad-1-project
    app.kubernetes.io/instance: squad-1-project
    app.kubernetes.io/name: squad-1-project-squad-1-project
  name: squad-1-project
spec:
  tls:
    termination: edge
  to:
    kind: Service
    name: squad-1-project
    weight: 100
  wildcardPolicy: None
